# Generated by Django 5.2.11 on 2026-02-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='vegetarian',
            field=models.BooleanField(default=False, help_text='Check if the member requires vegetarian meals', verbose_name='Vegetarian'),
        ),
    ]
