# Generated by Django 5.2.12 on 2026-03-07 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_registered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='division',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Division number (1-5)', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('division', models.PositiveSmallIntegerField(help_text='Division number (1-5)')),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['division', 'name'],
                'unique_together': {('division', 'name')},
            },
        ),
        migrations.AddField(
            model_name='member',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.unit'),
        ),
    ]
