# Generated by Django 5.2.12 on 2026-03-07 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_division_alter_room_capacity_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_divisions', models.PositiveSmallIntegerField(default=5, help_text='Total number of divisions for member assignment')),
                ('members_per_division', models.PositiveSmallIntegerField(default=20, help_text='Target number of members per division')),
                ('units_per_division', models.PositiveSmallIntegerField(default=2, help_text='Number of units per division')),
                ('members_per_unit', models.PositiveSmallIntegerField(default=10, help_text='Maximum number of members per unit')),
                ('default_room_capacity', models.PositiveSmallIntegerField(default=20, help_text='Default capacity for new rooms')),
                ('enable_auto_assignment', models.BooleanField(default=True, help_text='Enable automatic room/division/unit assignment for new members')),
                ('balance_by_church', models.BooleanField(default=True, help_text='Balance members across rooms/divisions based on church')),
                ('balance_by_district', models.BooleanField(default=True, help_text='Balance members across rooms/divisions based on district')),
                ('balance_by_gender', models.BooleanField(default=True, help_text='Separate rooms by gender when possible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
            },
        ),
        migrations.CreateModel(
            name='DivisionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_number', models.PositiveSmallIntegerField(help_text='Division number (1-based)')),
                ('custom_capacity', models.PositiveSmallIntegerField(help_text='Custom capacity for this division')),
                ('reason', models.TextField(blank=True, help_text='Reason for capacity override')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Division Capacity Override',
                'verbose_name_plural': 'Division Capacity Overrides',
                'unique_together': {('division_number',)},
            },
        ),
        migrations.CreateModel(
            name='RoomOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_capacity', models.PositiveSmallIntegerField(help_text='Custom capacity for this room (overrides system default)')),
                ('reason', models.TextField(blank=True, help_text='Reason for capacity override')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_override', to='members.room')),
            ],
            options={
                'verbose_name': 'Room Capacity Override',
                'verbose_name_plural': 'Room Capacity Overrides',
            },
        ),
        migrations.CreateModel(
            name='UnitOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_capacity', models.PositiveSmallIntegerField(help_text='Custom capacity for this unit')),
                ('reason', models.TextField(blank=True, help_text='Reason for capacity override')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_override', to='members.unit')),
            ],
            options={
                'verbose_name': 'Unit Capacity Override',
                'verbose_name_plural': 'Unit Capacity Overrides',
            },
        ),
    ]
